database: postgres:///bostonruby
page_title: relevancers
poll_interval: 10
org: 
  name: relevance.com
  href: http://thinkrelevance.com
opml: http://relevancers.herokuapp.com/relevance-blogs.xml
twitters: https://github.com/daemianmack/relevancers/wiki/All-Triangle-Rubyists
language: ruby
locations: 
- cambridge+ma 
- boston 
- somerville+ma 
- salem+ma 
- providence+ri 
- salem+ma 
- portsmouth+nh 
- portland+me
