database: postgres:///triangle-rubyists
page_title: Triangle Rubyists
poll_interval: 10
max_days_of_updates: 90
org: 
  name: github.com/daemianmack/triangle-rubyists
  href: https://github.com/daemianmack/triangle-rubyists
opml: http://triangle-rubyists.herokuapp.com/rubyist-blogs.xml
twitters: https://github.com/daemianmack/triangle-rubyists/wiki/All-Triangle-Rubyists
language: ruby
locations: 
- raleigh
- durham
- cary
- apex
- rtp
- research triangle area
- wake forest
- chapel hill
