page_title: relevancers
database: postgres:///triangle-rubyists
poll_interval: 10
org: 
  name: relevance.com
  href: http://thinkrelevance.com
opml: http://trianglerubyists.herokuapp.com/rubyist-blogs.xml
twitters: https://github.com/daemianmack/relevancers/wiki/All-Triangle-Rubyists
language: ruby
locations: 
- cambridge+ma 
- boston 
- somerville+ma 
- salem+ma 
- providence+ri 
- salem+ma 
- portsmouth+nh 
- portland+me
